apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf

data:
  status.conf: |
    server {
      listen 81;

      location /nginx_status {
        stub_status on;
      }

      location / {
        return 404;
      }
    }    
